### PR TITLE
Add processing.py & make pipeline InputTransformer

### PR DESCRIPTION
**Pull request by VallariAg**
1. Add all processing functions and libraries in processing.py
2. Make a custom transformer `InputTransformer` for preprocessing text
3. Add python's gitignore

### CODE REVIEW

**Comment by VallariAg** [comment]
Next steps: 
1. ~Get vocab and pass it to TfidfVectorizer~
2. ~convert_to_token() process whole dataset twice:  used in TfidfVectorizer and in make_vocab()~ 
3. ~Average Hypothesis Model~

**Comment by VallariAg** [comment]
So, I realized reading from a file would be faster than calculating vocabulary with make_vocab(). 
Now, we can run processing.py and it would write into a text file `vocabulary`, which can be imported when we run fake_news_detection.py
We can also edit the `vocabulary` manually so as to remove irrelevant words if found.

Update: Found some errors in last commit, lemme fix them

**Comment by VallariAg** [comment]
It takes about 40 minutes to train models and save vectorizer with vocabulary but predictions with app.py is still fast, so not a problem for users. But the model can be improved.

**Comment by TaniaMalhotra** [comment]
Great job!

**Pull request merged**
