### PR TITLE
Fixed UnicodeDecode Error

### PR DESCRIPTION
**Pull request by TaniaMalhotra**
Fixed  "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 263: invalid start byte"

### CODE REVIEW

**Comment by VallariAg** [comment]
Did you make any changes to the current status of the master branch? I don't get this error when I run it.
After adding ` engine = 'python', encoding='latin1'`, I get an error  "pandas.errors.ParserError: field larger than field limit (131072)". 
Just adding `encoding='latin1'` and not the `engine` part fixes the pandas error, though.

**Comment by TaniaMalhotra** [comment]
I got the unicode decode error when I tested your PR. Adding the engine and encoding solved it. 
Prolly you're not getting it 'cause our versions of python might be different(mine is 3.8.2)

**Comment by TaniaMalhotra** [comment]
Yeah, just the ```encoding=latin1``` part solves the error too!
I'll update my PR 😀

**Comment by VallariAg** [comment]
Yep, you're right! I've updated my Python's version now, thanks!

**Pull request merged**
